imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }
    validation: { enabled: true, enable_annotations: true }

web_profiler:
    toolbar: "%debug_toolbar%"
    #intercept_redirects: "%debug_redirects%"
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

assetic:
    use_controller: "%use_assetic_controller%"

# VichUploaderBundle
vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr

    mappings:
        post_image:
            #uri_prefix:         /images/posts
            uri_prefix:         /bundles/blogmain/images/posts/
            upload_destination: '%kernel.root_dir%/../web/bundles/blogmain/images/posts/'

#swiftmailer:
#    delivery_address: me@example.com
