blog_main_homepage:
    path:     /hello/{name}
    defaults: { _controller: BlogMainBundle:Default:index }

blog_main_feeds:
    path:     /blog
    defaults: { _controller: BlogMainBundle:Feeds:feeds }

blog_main_feeds_detail:
    path:     /blog/{id}
    defaults: { _controller: BlogMainBundle:Feeds:getById }

blog_main_feeds_detail_byUser:
    path:     /blog/{user}
    defaults: { _controller: BlogMainBundle:Feeds:getByUser }

blog_main_newForm:
    path:     /new
    defaults: { _controller: BlogMainBundle:Feeds:newForm }

blog_main_newPost:
    path:     /newPost/{user}/{title}/{content}
    defaults: { _controller: BlogMainBundle:Feeds:newPost, user: jonas, title: Test, content: Test }

blog_main_update:
    path:     /update/{id}
    defaults: { _controller: BlogMainBundle:Feeds:update }

blog_main_delete:
    path:     /delete/{id}
    defaults: { _controller: BlogMainBundle:Feeds:delete }
