blog_main_homepage:
    path:     /hello/{name}
    defaults: { _controller: BlogMainBundle:Default:index }

blog_main_feeds:
    path:     /blog
    defaults: { _controller: BlogMainBundle:Feeds:feeds }

blog_main_new:
    path:     /new
    defaults: { _controller: BlogMainBundle:Feeds:new }

blog_main_newPost:
    path:     /newPost/{title}/{content}
    defaults: { _controller: BlogMainBundle:Feeds:newPost, title: Test, content: Test }
